server:
  port: 8084

spring:
  application:
    name: CLOUD_GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: PRODUCT-CATALOG-SERVICE
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/product/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost